apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - name: ftp-connection
          containerPort: 21
        - name: ftp-data
          containerPort: 20
        - name: ftp-passive
          containerPort: 31000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  ports:
  - name: ftp-connection
    port: 21
    targetPort: 21
  - name: ftp-data
    port: 20
    targetPort: 20
  - name: ftp-passive
    port: 31000
    targetPort: 31000
  selector:
    app: ftps
  type: LoadBalancer
