apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb"
---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: influxdb-pv-claim
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-pv-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
      containers:
      - name: influxdb
        image: influxdb_img
        imagePullPolicy: Never
        ports:
        - name: indb
          containerPort: 8086
        volumeMounts:
        - name: influxdb-pv-storage
          mountPath: /var/lib/influxdb
        envFrom:
        - secretRef:
            name: influxdb-creds

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: influxdb
spec:
  ports:
  - name: infdb
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP